### ISSUE TITLE
Astropy 1.3 with old Numpies for Windows

### ISSUE THREAD

**Issue by astrofrog** [astropy/conda-channel-ci-extras#10]
It would be nice to have builds of Astropy 1.3 with old versions of Windows, but currently we only offer Linux:

https://anaconda.org/astropy-ci-extras/astropy/files?version=1.3

Is there a reason why we don't build these for Windows too?

**Comment by bsipocz** [comment]
@astrofrog - I think the only reason is that we never needed it for ci, and this channel is supposed to be existing to provide packages for our CIs. I suppose the machinery should be here already to do that.

However I think it would be valuable to make a wider variety of version combinations either in the astropy channel or on conda-forge?

**Comment by astrofrog** [comment]
I don't think we need to provide builds with old numpy versions in astropy or conda-forge, but it would be useful to have old numpies and windows here - I currently find myself needing that for glue CI.

**Comment by bsipocz** [comment]
glue CI is a good enough reason, are you opening a PR, or shall I?

**Comment by astrofrog** [comment]
I have no idea how this repo works, so if you know, please open a PR! :)

**Comment by bsipocz** [comment]
#11 should do the trick.

**Comment by astrofrog** [comment]
Thanks!
