### ISSUE TITLE
Disable copying from conda-forge

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-ci-extras#21]
The aim of this channel is to build version combinations that are unavailable on default or on conda forge, thus we need to disable copying from conda-forge:

https://travis-ci.org/astropy/conda-channel-ci-extras/jobs/260533244#L1080

**Comment by astrofrog** [comment]
Shall we close this?

**Comment by bsipocz** [comment]
Sure, I don't think we use this channel for anything any more.
