### ISSUE TITLE
New version combinations for astropy

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-ci-extras#4]
In many affiliated package matrix there is an astropy/numpy combinations that are not available in either conda channels. It would be great to build them here, so there won't be any need to install it via pip (although there are wheels available, so even the pip installs shouldn't take long). E.g.

- astropy stable (1.2.1) + python 3.5 + numpy 1.10
- astropy stable (1.2.1) + python 3.4 + numpy 1.9

Is there any reason not to extend the builds with older numpies here for the python3 versions, too?

**Comment by mwcraig** [comment]
Closed by https://github.com/astropy/conda-channel-ci-extras/commit/db1abdc0b652622fb6df3c496c0c20fe384d9771
